apiVersion: apps/v1
kind: Deployment
metadata:
  name: kt-backend
  namespace: envoy-ratelimit # Assuming same namespace as ratelimit service for simplicity, or default
  labels:
    app: kt-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kt-backend
  template:
    metadata:
      labels:
        app: kt-backend
        # agent.datadoghq.com/sidecar: fargate # Uncomment if running on Fargate
      annotations:
        ad.datadoghq.com/kt-backend.logs: '[{"source": "kt-backend", "service": "kt-backend"}]'
    spec:
      containers:
        - name: kt-backend
          image: leothenardo/kt-backend:2.1.4
          ports:
            - containerPort: 8080
          env:
            - name: RATELIMIT_HOST
              value: "envoy-ratelimit.envoy-ratelimit.svc.cluster.local"
            - name: RATELIMIT_PORT
              value: "8081"
            - name: RATELIMIT_TIMEOUT
              value: "1000"
            - name: RATELIMIT_FAIL_OPEN
              value: "true"
            - name: RATELIMIT_INCREMENT_SILVER
              value: "false"
            - name: RATELIMIT_INCREMENT_GOLD
              value: "true"
            - name: DD_SERVICE
              value: "kt-backend"
            - name: DD_ENV
              value: "production"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_AGENT_HOST
              value: "datadog-agent.datadog.svc.cluster.local"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_DOGSTATSD_PORT
              value: "8125"
          resources:
            requests:
              # cpu: "1400m"
              cpu: "600m"
              memory: "0.5Gi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: kt-backend
      nodeSelector:
        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: kt-backend
  namespace: envoy-ratelimit
spec:
  selector:
    app: kt-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
